name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use nodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
          BUCKET: reactgithubactions
          DIST: build
          REGION: us-east-1
          DIST_ID: EUW3CVJDSAAF3

      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build

      - name: Upload to s3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.REGION}}
      - run: aws s3 sync --delete ${{env.DIST}} s3://${{env.BUCKET}}

      - name: Upload to cloudfront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{env.DIST_ID}} \
            --paths "/*"
